export const countries = [
	{ value: 'Afghanistan', name: 'Afghanistan' },
	{ value: 'Albania', name: 'Albania' },
	{ value: 'Algeria', name: 'Algeria' },
	{ value: 'American Samoa', name: 'American Samoa' },
	{ value: 'Andorra', name: 'Andorra' },
	{ value: 'Angola', name: 'Angola' },
	{ value: 'Anguilla', name: 'Anguilla' },
	{ value: 'Antarctica', name: 'Antarctica' },
	{ value: 'Antigua and Barbuda', name: 'Antigua and Barbuda' },
	{ value: 'Argentina', name: 'Argentina' },
	{ value: 'Armenia', name: 'Armenia' },
	{ value: 'Aruba', name: 'Aruba' },
	{ value: 'Australia', name: 'Australia' },
	{ value: 'Austria', name: 'Austria' },
	{ value: 'Azerbaijan', name: 'Azerbaijan' },
	{ value: 'Bahamas (the)', name: 'Bahamas (the)' },
	{ value: 'Bahrain', name: 'Bahrain' },
	{ value: 'Bangladesh', name: 'Bangladesh' },
	{ value: 'Barbados', name: 'Barbados' },
	{ value: 'Belarus', name: 'Belarus' },
	{ value: 'Belgium', name: 'Belgium' },
	{ value: 'Belize', name: 'Belize' },
	{ value: 'Benin', name: 'Benin' },
	{ value: 'Bermuda', name: 'Bermuda' },
	{ value: 'Bhutan', name: 'Bhutan' },
	{ value: 'Bolivia (Plurinational State of)', name: 'Bolivia (Plurinational State of)' },
	{ value: 'Bonaire, Sint Eustatius and Saba', name: 'Bonaire, Sint Eustatius and Saba' },
	{ value: 'Bosnia and Herzegovina', name: 'Bosnia and Herzegovina' },
	{ value: 'Botswana', name: 'Botswana' },
	{ value: 'Bouvet Island', name: 'Bouvet Island' },
	{ value: 'Brazil', name: 'Brazil' },
	{ value: 'British Indian Ocean Territory (the)', name: 'British Indian Ocean Territory (the)' },
	{ value: 'Brunei Darussalam', name: 'Brunei Darussalam' },
	{ value: 'Bulgaria', name: 'Bulgaria' },
	{ value: 'Burkina Faso', name: 'Burkina Faso' },
	{ value: 'Burundi', name: 'Burundi' },
	{ value: 'Cabo Verde', name: 'Cabo Verde' },
	{ value: 'Cambodia', name: 'Cambodia' },
	{ value: 'Cameroon', name: 'Cameroon' },
	{ value: 'Canada', name: 'Canada' },
	{ value: 'Cayman Islands (the)', name: 'Cayman Islands (the)' },
	{ value: 'Central African Republic (the)', name: 'Central African Republic (the)' },
	{ value: 'Chad', name: 'Chad' },
	{ value: 'Chile', name: 'Chile' },
	{ value: 'China', name: 'China' },
	{ value: 'Christmas Island', name: 'Christmas Island' },
	{ value: 'Cocos (Keeling) Islands (the)', name: 'Cocos (Keeling) Islands (the)' },
	{ value: 'Colombia', name: 'Colombia' },
	{ value: 'Comoros (the)', name: 'Comoros (the)' },
	{
		value: 'Congo (the Democratic Republic of the)',
		name: 'Congo (the Democratic Republic of the)'
	},
	{ value: 'Congo (the)', name: 'Congo (the)' },
	{ value: 'Cook Islands (the)', name: 'Cook Islands (the)' },
	{ value: 'Costa Rica', name: 'Costa Rica' },
	{ value: 'Croatia', name: 'Croatia' },
	{ value: 'Cuba', name: 'Cuba' },
	{ value: 'Curaçao', name: 'Curaçao' },
	{ value: 'Cyprus', name: 'Cyprus' },
	{ value: 'Czechia', name: 'Czechia' },
	{ value: "Côte d'Ivoire", name: "Côte d'Ivoire" },
	{ value: 'Denmark', name: 'Denmark' },
	{ value: 'Djibouti', name: 'Djibouti' },
	{ value: 'Dominica', name: 'Dominica' },
	{ value: 'Dominican Republic (the)', name: 'Dominican Republic (the)' },
	{ value: 'Ecuador', name: 'Ecuador' },
	{ value: 'Egypt', name: 'Egypt' },
	{ value: 'El Salvador', name: 'El Salvador' },
	{ value: 'Equatorial Guinea', name: 'Equatorial Guinea' },
	{ value: 'Eritrea', name: 'Eritrea' },
	{ value: 'Estonia', name: 'Estonia' },
	{ value: 'Eswatini', name: 'Eswatini' },
	{ value: 'Ethiopia', name: 'Ethiopia' },
	{ value: 'Falkland Islands (the) [Malvinas]', name: 'Falkland Islands (the) [Malvinas]' },
	{ value: 'Faroe Islands (the)', name: 'Faroe Islands (the)' },
	{ value: 'Fiji', name: 'Fiji' },
	{ value: 'Finland', name: 'Finland' },
	{ value: 'France', name: 'France' },
	{ value: 'French Guiana', name: 'French Guiana' },
	{ value: 'French Polynesia', name: 'French Polynesia' },
	{ value: 'French Southern Territories (the)', name: 'French Southern Territories (the)' },
	{ value: 'Gabon', name: 'Gabon' },
	{ value: 'Gambia (the)', name: 'Gambia (the)' },
	{ value: 'Georgia', name: 'Georgia' },
	{ value: 'Germany', name: 'Germany' },
	{ value: 'Ghana', name: 'Ghana' },
	{ value: 'Gibraltar', name: 'Gibraltar' },
	{ value: 'Greece', name: 'Greece' },
	{ value: 'Greenland', name: 'Greenland' },
	{ value: 'Grenada', name: 'Grenada' },
	{ value: 'Guadeloupe', name: 'Guadeloupe' },
	{ value: 'Guam', name: 'Guam' },
	{ value: 'Guatemala', name: 'Guatemala' },
	{ value: 'Guernsey', name: 'Guernsey' },
	{ value: 'Guinea', name: 'Guinea' },
	{ value: 'Guinea-Bissau', name: 'Guinea-Bissau' },
	{ value: 'Guyana', name: 'Guyana' },
	{ value: 'Haiti', name: 'Haiti' },
	{ value: 'Heard Island and McDonald Islands', name: 'Heard Island and McDonald Islands' },
	{ value: 'Holy See (the)', name: 'Holy See (the)' },
	{ value: 'Honduras', name: 'Honduras' },
	{ value: 'Hong Kong', name: 'Hong Kong' },
	{ value: 'Hungary', name: 'Hungary' },
	{ value: 'Iceland', name: 'Iceland' },
	{ value: 'India', name: 'India' },
	{ value: 'Indonesia', name: 'Indonesia' },
	{ value: 'Iran (Islamic Republic of)', name: 'Iran (Islamic Republic of)' },
	{ value: 'Iraq', name: 'Iraq' },
	{ value: 'Ireland', name: 'Ireland' },
	{ value: 'Isle of Man', name: 'Isle of Man' },
	{ value: 'Israel', name: 'Israel' },
	{ value: 'Italy', name: 'Italy' },
	{ value: 'Jamaica', name: 'Jamaica' },
	{ value: 'Japan', name: 'Japan' },
	{ value: 'Jersey', name: 'Jersey' },
	{ value: 'Jordan', name: 'Jordan' },
	{ value: 'Kazakhstan', name: 'Kazakhstan' },
	{ value: 'Kenya', name: 'Kenya' },
	{ value: 'Kiribati', name: 'Kiribati' },
	{
		value: "Korea (the Democratic People's Republic of)",
		name: "Korea (the Democratic People's Republic of)"
	},
	{ value: 'Korea (the Republic of)', name: 'Korea (the Republic of)' },
	{ value: 'Kuwait', name: 'Kuwait' },
	{ value: 'Kyrgyzstan', name: 'Kyrgyzstan' },
	{
		value: "Lao People's Democratic Republic (the)",
		name: "Lao People's Democratic Republic (the)"
	},
	{ value: 'Latvia', name: 'Latvia' },
	{ value: 'Lebanon', name: 'Lebanon' },
	{ value: 'Lesotho', name: 'Lesotho' },
	{ value: 'Liberia', name: 'Liberia' },
	{ value: 'Libya', name: 'Libya' },
	{ value: 'Liechtenstein', name: 'Liechtenstein' },
	{ value: 'Lithuania', name: 'Lithuania' },
	{ value: 'Luxembourg', name: 'Luxembourg' },
	{ value: 'Macao', name: 'Macao' },
	{ value: 'Madagascar', name: 'Madagascar' },
	{ value: 'Malawi', name: 'Malawi' },
	{ value: 'Malaysia', name: 'Malaysia' },
	{ value: 'Maldives', name: 'Maldives' },
	{ value: 'Mali', name: 'Mali' },
	{ value: 'Malta', name: 'Malta' },
	{ value: 'Marshall Islands (the)', name: 'Marshall Islands (the)' },
	{ value: 'Martinique', name: 'Martinique' },
	{ value: 'Mauritania', name: 'Mauritania' },
	{ value: 'Mauritius', name: 'Mauritius' },
	{ value: 'Mayotte', name: 'Mayotte' },
	{ value: 'Mexico', name: 'Mexico' },
	{ value: 'Micronesia (Federated States of)', name: 'Micronesia (Federated States of)' },
	{ value: 'Moldova (the Republic of)', name: 'Moldova (the Republic of)' },
	{ value: 'Monaco', name: 'Monaco' },
	{ value: 'Mongolia', name: 'Mongolia' },
	{ value: 'Montenegro', name: 'Montenegro' },
	{ value: 'Montserrat', name: 'Montserrat' },
	{ value: 'Morocco', name: 'Morocco' },
	{ value: 'Mozambique', name: 'Mozambique' },
	{ value: 'Myanmar', name: 'Myanmar' },
	{ value: 'Namibia', name: 'Namibia' },
	{ value: 'Nauru', name: 'Nauru' },
	{ value: 'Nepal', name: 'Nepal' },
	{ value: 'Netherlands (the)', name: 'Netherlands (the)' },
	{ value: 'New Caledonia', name: 'New Caledonia' },
	{ value: 'New Zealand', name: 'New Zealand' },
	{ value: 'Nicaragua', name: 'Nicaragua' },
	{ value: 'Niger (the)', name: 'Niger (the)' },
	{ value: 'Nigeria', name: 'Nigeria' },
	{ value: 'Niue', name: 'Niue' },
	{ value: 'Norfolk Island', name: 'Norfolk Island' },
	{ value: 'Northern Mariana Islands (the)', name: 'Northern Mariana Islands (the)' },
	{ value: 'Norway', name: 'Norway' },
	{ value: 'Oman', name: 'Oman' },
	{ value: 'Pakistan', name: 'Pakistan' },
	{ value: 'Palau', name: 'Palau' },
	{ value: 'Palestine, State of', name: 'Palestine, State of' },
	{ value: 'Panama', name: 'Panama' },
	{ value: 'Papua New Guinea', name: 'Papua New Guinea' },
	{ value: 'Paraguay', name: 'Paraguay' },
	{ value: 'Peru', name: 'Peru' },
	{ value: 'Philippines (the)', name: 'Philippines (the)' },
	{ value: 'Pitcairn', name: 'Pitcairn' },
	{ value: 'Poland', name: 'Poland' },
	{ value: 'Portugal', name: 'Portugal' },
	{ value: 'Puerto Rico', name: 'Puerto Rico' },
	{ value: 'Qatar', name: 'Qatar' },
	{ value: 'Republic of North Macedonia', name: 'Republic of North Macedonia' },
	{ value: 'Romania', name: 'Romania' },
	{ value: 'Russian Federation (the)', name: 'Russian Federation (the)' },
	{ value: 'Rwanda', name: 'Rwanda' },
	{ value: 'Réunion', name: 'Réunion' },
	{ value: 'Saint Barthélemy', name: 'Saint Barthélemy' },
	{
		value: 'Saint Helena, Ascension and Tristan da Cunha',
		name: 'Saint Helena, Ascension and Tristan da Cunha'
	},
	{ value: 'Saint Kitts and Nevis', name: 'Saint Kitts and Nevis' },
	{ value: 'Saint Lucia', name: 'Saint Lucia' },
	{ value: 'Saint Martin (French part)', name: 'Saint Martin (French part)' },
	{ value: 'Saint Pierre and Miquelon', name: 'Saint Pierre and Miquelon' },
	{ value: 'Saint Vincent and the Grenadines', name: 'Saint Vincent and the Grenadines' },
	{ value: 'Samoa', name: 'Samoa' },
	{ value: 'San Marino', name: 'San Marino' },
	{ value: 'Sao Tome and Principe', name: 'Sao Tome and Principe' },
	{ value: 'Saudi Arabia', name: 'Saudi Arabia' },
	{ value: 'Senegal', name: 'Senegal' },
	{ value: 'Serbia', name: 'Serbia' },
	{ value: 'Seychelles', name: 'Seychelles' },
	{ value: 'Sierra Leone', name: 'Sierra Leone' },
	{ value: 'Singapore', name: 'Singapore' },
	{ value: 'Sint Maarten (Dutch part)', name: 'Sint Maarten (Dutch part)' },
	{ value: 'Slovakia', name: 'Slovakia' },
	{ value: 'Slovenia', name: 'Slovenia' },
	{ value: 'Solomon Islands', name: 'Solomon Islands' },
	{ value: 'Somalia', name: 'Somalia' },
	{ value: 'South Africa', name: 'South Africa' },
	{
		value: 'South Georgia and the South Sandwich Islands',
		name: 'South Georgia and the South Sandwich Islands'
	},
	{ value: 'South Sudan', name: 'South Sudan' },
	{ value: 'Spain', name: 'Spain' },
	{ value: 'Sri Lanka', name: 'Sri Lanka' },
	{ value: 'Sudan (the)', name: 'Sudan (the)' },
	{ value: 'Suriname', name: 'Suriname' },
	{ value: 'Svalbard and Jan Mayen', name: 'Svalbard and Jan Mayen' },
	{ value: 'Sweden', name: 'Sweden' },
	{ value: 'Switzerland', name: 'Switzerland' },
	{ value: 'Syrian Arab Republic', name: 'Syrian Arab Republic' },
	{ value: 'Taiwan', name: 'Taiwan' },
	{ value: 'Tajikistan', name: 'Tajikistan' },
	{ value: 'Tanzania, United Republic of', name: 'Tanzania, United Republic of' },
	{ value: 'Thailand', name: 'Thailand' },
	{ value: 'Timor-Leste', name: 'Timor-Leste' },
	{ value: 'Togo', name: 'Togo' },
	{ value: 'Tokelau', name: 'Tokelau' },
	{ value: 'Tonga', name: 'Tonga' },
	{ value: 'Trinidad and Tobago', name: 'Trinidad and Tobago' },
	{ value: 'Tunisia', name: 'Tunisia' },
	{ value: 'Turkey', name: 'Turkey' },
	{ value: 'Turkmenistan', name: 'Turkmenistan' },
	{ value: 'Turks and Caicos Islands (the)', name: 'Turks and Caicos Islands (the)' },
	{ value: 'Tuvalu', name: 'Tuvalu' },
	{ value: 'Uganda', name: 'Uganda' },
	{ value: 'Ukraine', name: 'Ukraine' },
	{ value: 'United Arab Emirates (the)', name: 'United Arab Emirates (the)' },
	{
		value: 'United Kingdom of Great Britain and Northern Ireland (the)',
		name: 'United Kingdom of Great Britain and Northern Ireland (the)'
	},
	{
		value: 'United States Minor Outlying Islands (the)',
		name: 'United States Minor Outlying Islands (the)'
	},
	{ value: 'United States of America (the)', name: 'United States of America (the)' },
	{ value: 'Uruguay', name: 'Uruguay' },
	{ value: 'Uzbekistan', name: 'Uzbekistan' },
	{ value: 'Vanuatu', name: 'Vanuatu' },
	{ value: 'Venezuela (Bolivarian Republic of)', name: 'Venezuela (Bolivarian Republic of)' },
	{ value: 'Viet Nam', name: 'Viet Nam' },
	{ value: 'Virgin Islands (British)', name: 'Virgin Islands (British)' },
	{ value: 'Virgin Islands (U.S.)', name: 'Virgin Islands (U.S.)' },
	{ value: 'Wallis and Futuna', name: 'Wallis and Futuna' },
	{ value: 'Western Sahara', name: 'Western Sahara' },
	{ value: 'Yemen', name: 'Yemen' },
	{ value: 'Zambia', name: 'Zambia' },
	{ value: 'Zimbabwe', name: 'Zimbabwe' },
	{ value: 'Åland Islands', name: 'Åland Islands' }
];

export const districts = [
	{
		name: 'Central',
		value: 'CEN',
		settlements: [
			{ name: 'Serowe', value: 'Serowe' },
			{ name: 'Palapye', value: 'Palapye' },
			{ name: 'Mahalapye', value: 'Mahalapye' },
			{ name: 'Bobonong', value: 'Bobonong' },
			{ name: 'Letlhakeng', value: 'Letlhakeng' },
			{ name: 'Mochudi', value: 'Mochudi' },
			{ name: 'Borolong', value: 'Borolong' },
			{ name: 'Chadibe', value: 'Chadibe' },
			{ name: 'Gweta', value: 'Gweta' },
			{ name: 'Sefhare', value: 'Sefhare' },
			{ name: 'Sefophe', value: 'Sefophe' },
			{ name: 'Selebi-Phikwe', value: 'Selebi-Phikwe' },
			{ name: 'Mmadinare', value: 'Mmadinare' },
			{ name: 'Shoshong', value: 'Shoshong' },
			{ name: 'Sowa', value: 'Sowa' },
			{ name: 'Orapa', value: 'Orapa' },
			{ name: 'Tonota', value: 'Tonota' },
			{ name: 'Tutume', value: 'Tutume' },
			{ name: 'Tsienyane', value: 'Tsienyane' },
			{ name: 'Lerala', value: 'Lerala' },
			{ name: 'Maitengwe', value: 'Maitengwe' },
			{ name: 'Mathangwane', value: 'Mathangwane' },
			{ name: 'Nata', value: 'Nata' },
			{ name: 'Tsetsebjwe', value: 'Tsetsebjwe' },
			{ name: 'Shashe-Mooke', value: 'Shashe-Mooke' }
		]
	},
	{
		name: 'Ghanzi',
		value: 'GHA',
		settlements: [
			{ name: 'Ghanzi', value: 'Ghanzi' },
			{ name: 'Charles Hill', value: 'Charles Hill' }
		]
	},
	{
		name: 'Kgalagadi',
		value: 'KGA',
		settlements: [
			{ name: 'Tsabong', value: 'Tsabong' },
			{ name: 'Hukuntsi', value: 'Hukuntsi' },
			{ name: 'Kang', value: 'Kang' }
		]
	},
	{
		name: 'Kgatleng',
		value: 'KGL',
		settlements: [
			{ name: 'Mochudi', value: 'Mochudi' },
			{ name: 'Bokaa', value: 'Bokaa' },
			{ name: 'Oodi', value: 'Oodi' },
			{ name: 'Rasesa', value: 'Rasesa' },
			{ name: 'Morwa', value: 'Morwa' }
		]
	},
	{
		name: 'Kweneng',
		value: 'KWE',
		settlements: [
			{ name: 'Molepolole', value: 'Molepolole' },
			{ name: 'Mogoditshane', value: 'Mogoditshane' },
			{ name: 'Thamaga', value: 'Thamaga' },
			{ name: 'Gabane', value: 'Gabane' },
			{ name: 'Kopong', value: 'Kopong' },
			{ name: 'Kumakwane', value: 'Kumakwane' },
			{ name: 'Lentsweletau', value: 'Lentsweletau' },
			{ name: 'Letlhakeng', value: 'Letlhakeng' },
			{ name: 'Metsimotlhaba', value: 'Metsimotlhaba' },
			{ name: 'Mmankgodi', value: 'Mmankgodi' },
			{ name: 'Mmopane', value: 'Mmopane' }
		]
	},
	{
		name: 'Ngamiland',
		value: 'NWE',
		settlements: [
			{ name: 'Maun', value: 'Maun' },
			{ name: 'Gumare', value: 'Gumare' },
			{ name: 'Shakawe', value: 'Shakawe' },
			{ name: 'Etsha', value: 'Etsha' },
			{ name: 'Kasane', value: 'Kasane' }
		]
	},
	{
		name: 'North East',
		value: 'NEA',
		settlements: [
			{ name: 'Francistown', value: 'Francistown' },
			{ name: 'Masunga', value: 'Masunga' },
			{ name: 'Selebi-Phikwe', value: 'Selebi-Phikwe' },
			{ name: 'Tati Siding', value: 'Tati Siding' }
		]
	},
	{
		name: 'South East',
		value: 'SEA',
		settlements: [
			{ name: 'Ramotswa', value: 'Ramotswa' },
			{ name: 'Gaborone', value: 'Gaborone' },
			{ name: 'Tlokweng', value: 'Tlokweng' },
			{ name: 'Kanye', value: 'Kanye' },
			{ name: 'Moshupa', value: 'Moshupa' },
			{ name: 'Otse', value: 'Otse' },
			{ name: 'Lobatse', value: 'Lobatse' },
			{ name: 'Ramotswa Station/Taung', value: 'Ramotswa Station/Taung' }
		]
	},
	{
		name: 'Southern',
		value: 'SOU',
		settlements: [
			{ name: 'Kanye', value: 'Kanye' },
			{ name: 'Jwaneng', value: 'Jwaneng' },
			{ name: 'Moshupa', value: 'Moshupa' },
			{ name: 'Goodhope', value: 'Goodhope' },
			{ name: 'Lotlhakane', value: 'Lotlhakane' },
			{ name: 'Mmathethe', value: 'Mmathethe' },
			{ name: 'Molapowabojang', value: 'Molapowabojang' },
			{ name: 'Sese', value: 'Sese' }
		]
	}
];
